fix: restore UTF-8 deployment files

diff --git a/.github/workflows/terraform-deploy.yml b/.github/workflows/terraform-deploy.yml
--- a/.github/workflows/terraform-deploy.yml
+++ b/.github/workflows/terraform-deploy.yml
@@ -1,1 +1,171 @@
-þŠmþ&yºÞÃòân¶«Ëñè™æë{Ü™ßì…éez{ì†X§{_?n)ÿ¦Ã©z¶­Š‰ç¢Ú^®h­µç[˜[YNˆ\œ˜Y›Ü›H\ÞB‚›ÛŽ‚ˆÛÜšÙ›Ý×Ù\Ü]Ú‚ˆ[œ]Î‚ˆ\N‚ˆ\ØÜš\[ÛŽˆ\HH™]šY]ÙY[ˆY\ˆ[š\›Û›Y[\›Ý˜[ˆ™\]Z\™YˆYBˆ\Nˆ›ÛÛX[‚ˆY˜][ˆ˜[ÙB‚œ\›Z\ÜÚ[ÛœÎ‚ˆÛÛ[Îˆ™XYˆY]ÚÙ[ŽˆÜš]B‚˜ÛÛ˜Ý\œ™[˜ÞN‚ˆÜ›Ý\ˆ\œ˜Y›Ü›K\Ú\™YZ[™œ˜\ÝXÝ\™BˆØ[˜Ù[Z[‹\›ÙÜ™\ÜÎˆ˜[ÙB‚™[Ž‚ˆ—ÒS—ÐUUÓPUSÓŽˆYH‚ˆ—ÒS”Uˆ™˜[ÙH‚ˆ—ÔÕUWÐ•PÒÑUˆ	ÞÈ˜\œË•—ÔÕUWÐ•PÒÑU_Bˆ—ÔÕUWÒÑVNˆ	ÞÈ˜\œË•—ÔÕUWÒÑVH_Bˆ—ÔÕUWÕP“TÕÔ‘WÑS‘ÒS•ˆ	ÞÈ˜\œË•—ÔÕUWÕP“TÕÔ‘WÑS‘ÒS•_Bˆ—ÔÕUWÕP“TÕÔ‘WÕP“Nˆ	ÞÈ˜\œË•—ÔÕUWÕP“TÕÔ‘WÕP“H_BˆSPÓÕQÔ‘QÒSÓŽˆ	ÞÈ˜\œËSPÓÕQÔ‘QÒSÓˆ_BˆSPÓÕQÓÒQ×Ô“Õ’QT—ÐT“Žˆ	ÞÈ˜\œËSPÓÕQÓÒQ×Ô“Õ’QT—ÐT“ˆ_BˆSPÓÕQÔS—Ô“ÓWÐT“Žˆ	ÞÈ˜\œËSPÓÕQÔS—Ô“ÓWÐT“ˆ_BˆSPÓÕQÐTWÔ“ÓWÐT“Žˆ	ÞÈ˜\œËSPÓÕQÐTWÔ“ÓWÐT“ˆ_B‚š›ØœÎ‚ˆ[Ž‚ˆ˜[YNˆ[‚ˆ[œË[ÛŽˆX[K[]\Ýˆ[š\›Û›Y[ˆ\œ˜Y›Ü›K\[‚ˆY˜][Î‚ˆ[Ž‚ˆÛÜšÚ[™ËY\™XÝÜžNˆ\œ˜Y›Ü›Bˆ[Ž‚ˆ—ÕT—Ü™YÚ[ÛŽˆ	ÞÈ˜\œËSPÓÕQÔ‘QÒSÓˆ_Bˆ—ÕT—Ø]˜Z[Xš[]WÞ›Û™\Îˆ	ÞÈ˜\œË•—ÐURSP’SUWÖ“Ó‘TÈ_Bˆ—ÕT—ÝœÝÚ]ÚØÚYœÎˆ	ÞÈ˜\œË•—Õ”ÕÒUÒÐÒQ”È_Bˆ—ÕT—ØYZ[—ØÚYŽˆ	ÞÈ˜\œË•—ÐQRS—ÐÒQˆ_Bˆ—ÕT—Ú[œÝ[˜ÙWÝ\Nˆ	ÞÈ˜\œË•—ÒS”ÕSÑWÕTH_Bˆ—ÕT—Ú[XYÙWÚYˆ	ÞÈ˜\œË•—ÒSPQÑWÒQ_Bˆ—ÕT—ÛÜÜ×ØXÚÙ]Û˜[YNˆ	ÞÈ˜\œË•—ÓÔÔ×Ð•PÒÑUÓSQH_Bˆ—ÕT—Ù[˜X›WØ[Žˆ	ÞÈ˜\œË•—ÑSP“WÐSˆ_Bˆ—ÕT—ÜÜÚÜX›X×ÚÙ^Nˆ	ÞÈÙXÜ™]Ë•—ÔÔÒÔP“P×ÒÑVH_BˆÝ\Î‚ˆH˜[YNˆÚXÚÛÝ]ÛÝ\˜ÙHÛÙBˆ\Ù\ÎˆXÝ[ÛœËØÚXÚÛÝ]B‚ˆH˜[YNˆ™\ÝšXÝ\Þ[Y[ÈÈXZ[‚ˆ[Žˆ\Ý‰ÒUP—Ô‘QˆˆHœ™YœËÚXYËÛXZ[ˆ‚‚ˆH˜[YNˆÚXÚÈ™\]Z\™YÛÛ™šYÝ\˜][Û‚ˆÚ[ˆ˜\Úˆ[ŽˆˆZ\ÜÚ[™ÏLˆ›Üˆ˜[YH[ˆˆ—ÔÕUWÐ•PÒÑU—ÔÕUWÒÑVH—ÔÕUWÕP“TÕÔ‘WÑS‘ÒS•ˆ—ÔÕUWÕP“TÕÔ‘WÕP“HSPÓÕQÔ‘QÒSÓˆˆSPÓÕQÓÒQ×Ô“Õ’QT—ÐT“ˆSPÓÕQÔS—Ô“ÓWÐT“ˆˆSPÓÕQÐTWÔ“ÓWÐT“ˆˆ—ÕT—Ø]˜Z[Xš[]WÞ›Û™\È—ÕT—ÝœÝÚ]ÚØÚYœÈˆ—ÕT—ØYZ[—ØÚYˆ—ÕT—Ú[œÝ[˜ÙWÝ\H—ÕT—Ú[XYÙWÚYˆ—ÕT—ÛÜÜ×ØXÚÙ]Û˜[YH—ÕT—Ù[˜X›WØ[ˆ—ÕT—ÜÜÚÜX›X×ÚÙ^NÈÂˆYˆÖÈ^ˆ‰È[˜[Y_HˆWNÈ[‚ˆXÚÈŽŽ™\œ›ÜŽŽ“Z\ÜÚ[™ÈÚ]XˆÛÛ™šYÝ\˜][ÛŽˆ	Û˜[Y_H‚ˆZ\ÜÚ[™ÏLBˆšBˆÛ™Bˆ^]‰Z\ÜÚ[™È‚‚ˆH˜[YNˆÙ]\\œ˜Y›Ü›Bˆ\Ù\Îˆ\ÚXÛÜœÜÙ]\]\œ˜Y›Ü›PŒÂˆÚ]‚ˆ\œ˜Y›Ü›WÝ™\œÚ[ÛŽˆŒKŒMKH‚‚ˆH˜[YNˆ]][XØ]HÈ[X˜X˜HÛÝYÚ]ÒQÂˆ\Ù\Îˆ[^][‹ØÛÛ™šYÝ\™KX[^][‹XÜ™Y[X[ËXXÝ[ÛYMLÎYLØNÎXXÌÍMŽLNXMÌÍYMÎYM‚ˆÚ]‚ˆÚYË\›ÝšY\‹X\›Žˆ	ÞÈ[‹SPÓÕQÓÒQ×Ô“Õ’QT—ÐT“ˆ_Bˆ›ÛK]ËX\ÜÝ[YNˆ	ÞÈ[‹SPÓÕQÔS—Ô“ÓWÐT“ˆ_Bˆ›ÛK\Ù\ÜÚ[Û‹[˜[YNˆÚ]X‹]\œ˜Y›Ü›K\[‚ˆ›ÛK\Ù\ÜÚ[Û‹Y^\˜][ÛŽˆNˆ]YY[˜ÙNˆÝË˜[^][˜ÜË˜ÛÛB‚ˆH˜[YNˆ[š]X[^™H[˜Üž\Y™[[ÝHÝ]HÚ]ØÚÚ[™Âˆ[Žˆˆ\œ˜Y›Ü›H[š]ˆX˜XÚÙ[™XÛÛ™šYÏH˜XÚÙ]IÕ—ÔÕUWÐ•PÒÑUHˆˆX˜XÚÙ[™XÛÛ™šYÏHšÙ^OIÕ—ÔÕUWÒÑV_HˆˆX˜XÚÙ[™XÛÛ™šYÏHœ™YÚ[ÛIÐSPÓÕQÔ‘QÒSÓŸHˆˆX˜XÚÙ[™XÛÛ™šYÏH™[˜Üž\]YHˆˆX˜XÚÙ[™XÛÛ™šYÏH˜XÛ\š]˜]HˆˆX˜XÚÙ[™XÛÛ™šYÏHX›\ÝÜ™WÙ[™Ú[IÕ—ÔÕUWÕP“TÕÔ‘WÑS‘ÒS•HˆˆX˜XÚÙ[™XÛÛ™šYÏHX›\ÝÜ™WÝX›OIÕ—ÔÕUWÕP“TÕÔ‘WÕP“_H‚‚ˆH˜[YNˆÜ™X]H^XÝ][Ûˆ[‚ˆ[Žˆ\œ˜Y›Ü›H[ˆ[ØÚË][Y[Ý]M[H[Ý]]œ[‚‚ˆH˜[YNˆY[ˆÈH[ˆÝ[[X\žBˆ[ŽˆˆÂˆXÚÈˆÈÈÈ\œ˜Y›Ü›H[ˆ‚ˆXÚÈ	Ø^	Âˆ\œ˜Y›Ü›HÚÝÈ[›ËXÛÛÜˆœ[‚ˆXÚÈ	Ø	ÂˆHˆ‰ÒUP—ÔÕTÔÕSSPT–H‚‚ˆH˜[YNˆ\ØY[[]]X›H[‚ˆ\Ù\ÎˆXÝ[ÛœËÝ\ØYX\Y˜XÝˆÚ]‚ˆ˜[YNˆ\œ˜Y›Ü›K\[‹IÞÈÚ]X‹œÚH_KIÞÈÚ]X‹œ[—ÚY_Bˆ]ˆ\œ˜Y›Ü›KÝœ[‚ˆY‹[›ËYš[\ËY›Ý[™ˆ\œ›Ü‚ˆ™][[Û‹Y^\ÎˆB‚ˆ\N‚ˆ˜[YNˆ\›Ý˜[[™\BˆYŽˆ	ÞÈ[œ]Ë˜\H	‰ˆ™YYËœ[‹œ™\Ý[OH	ÜÝXØÙ\ÜÉÈ_Bˆ™YYÎˆ[‚ˆ[œË[ÛŽˆX[K[]\Ýˆ[š\›Û›Y[ˆ\œ˜Y›Ü›KX\BˆY˜][Î‚ˆ[Ž‚ˆÛÜšÚ[™ËY\™XÝÜžNˆ\œ˜Y›Ü›BˆÝ\Î‚ˆH˜[YNˆÚXÚÛÝ]H[›™Y™]š\Ú[Û‚ˆ\Ù\ÎˆXÝ[ÛœËØÚXÚÛÝ]BˆÚ]‚ˆ™YŽˆ	ÞÈÚ]X‹œÚH_B‚ˆH˜[YNˆ™\ÝšXÝ\Þ[Y[ÈÈXZ[‚ˆ[Žˆ\Ý‰ÒUP—Ô‘QˆˆHœ™YœËÚXYËÛXZ[ˆ‚‚ˆH˜[YNˆÙ]\\œ˜Y›Ü›Bˆ\Ù\Îˆ\ÚXÛÜœÜÙ]\]\œ˜Y›Ü›PŒÂˆÚ]‚ˆ\œ˜Y›Ü›WÝ™\œÚ[ÛŽˆŒKŒMKH‚‚ˆH˜[YNˆ]][XØ]HÈ[X˜X˜HÛÝYÚ]ÒQÂˆ\Ù\Îˆ[^][‹ØÛÛ™šYÝ\™KX[^][‹XÜ™Y[X[ËXXÝ[ÛYMLÎYLØNÎXXÌÍMŽLNXMÌÍYMÎYM‚ˆÚ]‚ˆÚYË\›ÝšY\‹X\›Žˆ	ÞÈ[‹SPÓÕQÓÒQ×Ô“Õ’QT—ÐT“ˆ_Bˆ›ÛK]ËX\ÜÝ[YNˆ	ÞÈ[‹SPÓÕQÐTWÔ“ÓWÐT“ˆ_Bˆ›ÛK\Ù\ÜÚ[Û‹[˜[YNˆÚ]X‹]\œ˜Y›Ü›KX\Bˆ›ÛK\Ù\ÜÚ[Û‹Y^\˜][ÛŽˆNˆ]YY[˜ÙNˆÝË˜[^][˜ÜË˜ÛÛB‚ˆH˜[YNˆ[š]X[^™H[˜Üž\Y™[[ÝHÝ]HÚ]ØÚÚ[™Âˆ[Žˆˆ\œ˜Y›Ü›H[š]ˆX˜XÚÙ[™XÛÛ™šYÏH˜XÚÙ]IÕ—ÔÕUWÐ•PÒÑUHˆˆX˜XÚÙ[™XÛÛ™šYÏHšÙ^OIÕ—ÔÕUWÒÑV_HˆˆX˜XÚÙ[™XÛÛ™šYÏHœ™YÚ[ÛIÐSPÓÕQÔ‘QÒSÓŸHˆˆX˜XÚÙ[™XÛÛ™šYÏH™[˜Üž\]YHˆˆX˜XÚÙ[™XÛÛ™šYÏH˜XÛ\š]˜]HˆˆX˜XÚÙ[™XÛÛ™šYÏHX›\ÝÜ™WÙ[™Ú[IÕ—ÔÕUWÕP“TÕÔ‘WÑS‘ÒS•HˆˆX˜XÚÙ[™XÛÛ™šYÏHX›\ÝÜ™WÝX›OIÕ—ÔÕUWÕP“TÕÔ‘WÕP“_H‚‚ˆH˜[YNˆÝÛ›ØYH\›Ý™Y[‚ˆ\Ù\ÎˆXÝ[ÛœËÙÝÛ›ØYX\Y˜XÝˆÚ]‚ˆ˜[YNˆ\œ˜Y›Ü›K\[‹IÞÈÚ]X‹œÚH_KIÞÈÚ]X‹œ[—ÚY_Bˆ]ˆ\œ˜Y›Ü›B‚ˆH˜[YNˆ\HH\›Ý™Y[‚ˆ[Žˆ\œ˜Y›Ü›H\H[ØÚË][Y[Ý]M[HX]]ËX\›Ý™Hœ[‚
+name: Terraform Deploy
+
+on:
+  workflow_dispatch:
+    inputs:
+      apply:
+        description: Apply the reviewed plan after environment approval
+        required: true
+        type: boolean
+        default: false
+
+permissions:
+  contents: read
+  id-token: write
+
+concurrency:
+  group: terraform-shared-infrastructure
+  cancel-in-progress: false
+
+env:
+  TF_IN_AUTOMATION: "true"
+  TF_INPUT: "false"
+  TF_STATE_BUCKET: ${{ vars.TF_STATE_BUCKET }}
+  TF_STATE_KEY: ${{ vars.TF_STATE_KEY }}
+  TF_STATE_TABLESTORE_ENDPOINT: ${{ vars.TF_STATE_TABLESTORE_ENDPOINT }}
+  TF_STATE_TABLESTORE_TABLE: ${{ vars.TF_STATE_TABLESTORE_TABLE }}
+  ALICLOUD_REGION: ${{ vars.ALICLOUD_REGION }}
+  ALICLOUD_OIDC_PROVIDER_ARN: ${{ vars.ALICLOUD_OIDC_PROVIDER_ARN }}
+  ALICLOUD_PLAN_ROLE_ARN: ${{ vars.ALICLOUD_PLAN_ROLE_ARN }}
+  ALICLOUD_APPLY_ROLE_ARN: ${{ vars.ALICLOUD_APPLY_ROLE_ARN }}
+
+jobs:
+  plan:
+    name: Plan
+    runs-on: ubuntu-latest
+    environment: terraform-plan
+    defaults:
+      run:
+        working-directory: terraform
+    env:
+      TF_VAR_region: ${{ vars.ALICLOUD_REGION }}
+      TF_VAR_availability_zones: ${{ vars.TF_AVAILABILITY_ZONES }}
+      TF_VAR_vswitch_cidrs: ${{ vars.TF_VSWITCH_CIDRS }}
+      TF_VAR_admin_cidr: ${{ vars.TF_ADMIN_CIDR }}
+      TF_VAR_instance_type: ${{ vars.TF_INSTANCE_TYPE }}
+      TF_VAR_image_id: ${{ vars.TF_IMAGE_ID }}
+      TF_VAR_oss_bucket_name: ${{ vars.TF_OSS_BUCKET_NAME }}
+      TF_VAR_enable_alb: ${{ vars.TF_ENABLE_ALB }}
+      TF_VAR_ssh_public_key: ${{ secrets.TF_SSH_PUBLIC_KEY }}
+    steps:
+      - name: Checkout source code
+        uses: actions/checkout@v5
+
+      - name: Restrict deployments to main
+        run: test "$GITHUB_REF" = "refs/heads/main"
+
+      - name: Check required configuration
+        shell: bash
+        run: |
+          missing=0
+          for name in \
+            TF_STATE_BUCKET TF_STATE_KEY TF_STATE_TABLESTORE_ENDPOINT \
+            TF_STATE_TABLESTORE_TABLE ALICLOUD_REGION \
+            ALICLOUD_OIDC_PROVIDER_ARN ALICLOUD_PLAN_ROLE_ARN \
+            ALICLOUD_APPLY_ROLE_ARN \
+            TF_VAR_availability_zones TF_VAR_vswitch_cidrs \
+            TF_VAR_admin_cidr TF_VAR_instance_type TF_VAR_image_id \
+            TF_VAR_oss_bucket_name TF_VAR_enable_alb TF_VAR_ssh_public_key; do
+            if [[ -z "${!name}" ]]; then
+              echo "::error::Missing GitHub configuration: ${name}"
+              missing=1
+            fi
+          done
+          exit "$missing"
+
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: "1.15.5"
+
+      - name: Authenticate to Alibaba Cloud with OIDC
+        uses: aliyun/configure-aliyun-credentials-action@1e5248c8d5d93a8781ac344a68e19a43341e79e6
+        with:
+          oidc-provider-arn: ${{ env.ALICLOUD_OIDC_PROVIDER_ARN }}
+          role-to-assume: ${{ env.ALICLOUD_PLAN_ROLE_ARN }}
+          role-session-name: github-terraform-plan
+          role-session-expiration: 1800
+          audience: sts.aliyuncs.com
+
+      - name: Initialize encrypted remote state with locking
+        run: |
+          terraform init \
+            -backend-config="bucket=${TF_STATE_BUCKET}" \
+            -backend-config="key=${TF_STATE_KEY}" \
+            -backend-config="region=${ALICLOUD_REGION}" \
+            -backend-config="encrypt=true" \
+            -backend-config="acl=private" \
+            -backend-config="tablestore_endpoint=${TF_STATE_TABLESTORE_ENDPOINT}" \
+            -backend-config="tablestore_table=${TF_STATE_TABLESTORE_TABLE}"
+
+      - name: Create execution plan
+        run: terraform plan -lock-timeout=5m -out=tfplan
+
+      - name: Add plan to the run summary
+        run: |
+          {
+            echo "### Terraform plan"
+            echo '```text'
+            terraform show -no-color tfplan
+            echo '```'
+          } >> "$GITHUB_STEP_SUMMARY"
+
+      - name: Upload immutable plan
+        uses: actions/upload-artifact@v4
+        with:
+          name: terraform-plan-${{ github.sha }}-${{ github.run_id }}
+          path: terraform/tfplan
+          if-no-files-found: error
+          retention-days: 1
+
+  apply:
+    name: Approval and apply
+    if: ${{ inputs.apply && needs.plan.result == 'success' }}
+    needs: plan
+    runs-on: ubuntu-latest
+    environment: terraform-apply
+    defaults:
+      run:
+        working-directory: terraform
+    steps:
+      - name: Checkout the planned revision
+        uses: actions/checkout@v5
+        with:
+          ref: ${{ github.sha }}
+
+      - name: Restrict deployments to main
+        run: test "$GITHUB_REF" = "refs/heads/main"
+
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: "1.15.5"
+
+      - name: Authenticate to Alibaba Cloud with OIDC
+        uses: aliyun/configure-aliyun-credentials-action@1e5248c8d5d93a8781ac344a68e19a43341e79e6
+        with:
+          oidc-provider-arn: ${{ env.ALICLOUD_OIDC_PROVIDER_ARN }}
+          role-to-assume: ${{ env.ALICLOUD_APPLY_ROLE_ARN }}
+          role-session-name: github-terraform-apply
+          role-session-expiration: 1800
+          audience: sts.aliyuncs.com
+
+      - name: Initialize encrypted remote state with locking
+        run: |
+          terraform init \
+            -backend-config="bucket=${TF_STATE_BUCKET}" \
+            -backend-config="key=${TF_STATE_KEY}" \
+            -backend-config="region=${ALICLOUD_REGION}" \
+            -backend-config="encrypt=true" \
+            -backend-config="acl=private" \
+            -backend-config="tablestore_endpoint=${TF_STATE_TABLESTORE_ENDPOINT}" \
+            -backend-config="tablestore_table=${TF_STATE_TABLESTORE_TABLE}"
+
+      - name: Download the approved plan
+        uses: actions/download-artifact@v4
+        with:
+          name: terraform-plan-${{ github.sha }}-${{ github.run_id }}
+          path: terraform
+
+      - name: Apply the approved plan
+        run: terraform apply -lock-timeout=5m -auto-approve tfplan
